### ISSUE TITLE
/nowplaying

### ISSUE THREAD

**Issue by Hachiiki** [hongduccodedao/Bot-Music-Discord-v13#2]
**Installing:**
- npm install

**Node Version:**
- v17.7.2

**Affected Version**
- 1.5.0

**Problem**
- khi sử dụng lệnh này, nó không gửi thông báo nhúng được cho là hiển thị bản nhạc đang phát hiện tại
- _English: when using this command it doesn't send embed message which is supposed to show current playing track_

**Error Showed in console**
```(node:4263) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (/home/runner/Bot-Music-Discord-v13/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:90:46)
    at Object.run (/home/runner/Bot-Music-Discord-v13/SlashCommands/music/nowplaying.js:29:21)
    at Client.<anonymous> (/home/runner/Bot-Music-Discord-v13/events/interactionCreate.js:24:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
} Promise {
  <rejected> Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
      at CommandInteraction.reply (/home/runner/Bot-Music-Discord-v13/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:90:46)
      at Object.run (/home/runner/Bot-Music-Discord-v13/SlashCommands/music/nowplaying.js:29:21)
      at Client.<anonymous> (/home/runner/Bot-Music-Discord-v13/events/interactionCreate.js:24:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
  }
}

**Comment by hongducdev** [comment]
I fixed it. You can use it again. Thanks for reporting it to me.
